## an index dataframe


index <- data.frame(
  category =  c(
    "End of Financial Year Positions",
    "End of Month Positions",
    "End of Month Positions",
    "End of Month Positions",
    "End of Month Positions",
    "End of Month Positions",
    "End of Month Positions",
    "End of Month Positions",
    "End of Month Positions",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Transactional Data",
    "Ownership of Australian Government Securities",
    "Ownership of Australian Government Securities",
    "AGS Secondary Market Turnover",
    "AGS Secondary Market Turnover",
    "Term Premium Estimates",
    "Other Historical Data Sets",
    "Other Historical Data Sets",
    "Other Historical Data Sets",
    "Other Historical Data Sets",
    "Other Historical Data Sets",
    "Other Historical Data Sets"
  ),
  title = c(
    "Executive Summary",
    "Portfolio Aggregate",
    "Portfolio Aggregate",
    "Treasury Bonds",
    "Treasury Bonds",
    "Treasury Indexed Bonds",
    "Treasury Indexed Bonds",
    "Treasury Notes",
    "Treasury Notes",
    "Treasury Bond Issuance",
    "Treasury Bond Issuance",
    "Treasury Bond Issuance",
    "Treasury Bond Buybacks",
    "Treasury Indexed Bond Issuance",
    "Treasury Indexed Bond Issuance",
    "Treasury Indexed Bond Buybacks",
    "Treasury Notes Issuance",
    "Retail Buyback Facility",
    "Securities Lending Facility",
    "Public Register of Government Borrowings",
    "Non-resident Holdings of AGS",
    "Secondary Market Turnover of Treasury Bonds",
    "Secondary Market Turnover of Treasury Indexed Bonds",
    "Term Premium Estimates",
    "Indexation Factors",
    "RMBS Transactions",
    "RMBS Auctions",
    "Interest Rate Swaps",
    "Cross Currency Swaps",
    "Portfolio Overview"
  ),
  despription =  c(
    "Overview of AGS outstanding and investments held.",
    "Dealt Basis. End of month AGS outstanding and investments held. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Settlement Basis. End of month AGS outstanding and investments held. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Dealt Basis. End of month outstanding volume for each security type and maturity. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Settlement Basis. End of month outstanding volume for each security type and maturity. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Dealt Basis. End of month outstanding volume for each security type and maturity. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Settlement Basis. End of month outstanding volume for each security type and maturity. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Dealt Basis. End of month outstanding volume for each security type and maturity. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Settlement Basis. End of month outstanding volume for each security type and maturity. Includes Face Value, Market Value, Delta, Duration and Tenor.",
    "Issuance via tender or syndication.",
    "Issuance via conversion or switch.",
    "Data from syndicated issues including investor details.",
    "Wholesale buybacks via tender, syndication or with the RBA.",
    "Issuance via tender, syndication, tap, panel or conversion.",
    "Data from syndicated issues including investor details.",
    "Wholesale buybacks via syndication or fixed price tender.",
    "Issuance via tender.",
    "Retail buybacks through the Buyback Facility.",
    "Bonds lent on an open term basis via the Securities Lending Facility.",
    "Beneficial ownership, by country, of all securities issued by the Australian Commonwealth Government and any securities guaranteed by the Commonwealth that are issued by Australian States or Territories.",
    "Non-resident holdings of AGS including adjustments made for activity in the repo market.",
    "Survey results from bond market intermediaries detailing their turnover in AGS. This data will be updated quarterly on the last business day of the month with a two month lag (i.e. on the last business day of May, August, November, and February each year).",
    "Survey results from bond market intermediaries detailing their turnover in AGS. This data will be updated quarterly on the last business day of the month with a two month lag (i.e. on the last business day of May, August, November, and February each year).",
    "Daily yield decomposition of Australian Treasury Bond term structure and term premium estimates.",
    "A time series of indexation factors for Treasury Indexed Bonds.",
    "A summary of AOFM participation in Residential Mortgage Backed Security (RMBS) transactions prior to 2020.",
    "A summary of AOFM RMBS auction results prior to 2020.",
    "AOFM transactions in Australian Dollar Interest Rate Swaps.",
    "AOFM transactions in Cross Currency Interest Rate Swaps.",
    "An overview of end of financial year outstanding amounts for AGS on issue prior to 2003."
  ),
  id = c(
    "eofy_executive_summary",
    "eom_portfolio_aggregate_dealt",
    "eom_portfolio_aggregate_settlement",
    "eom_tb_dealt",
    "eom_tb_settlement",
    "eom_tib_dealt",
    "eom_tib_settlement",
    "eom_tn_dealt",
    "eom_tn_settlement",
    "transactional_tb_issuance_tender_syn",
    "transactional_tb_issuance_conversion",
    "transactional_tb_issuance_syn_details",
    "transactional_tb_buybacks",
    "transactional_tib_issuance_tender_syn",
    "transactional_tib_issuance_syn_details",
    "transactional_tib_buybacks",
    "transactional_tn_issuance",
    "transactional_retail_buybacks",
    "transactional_securities_lending_facility",
    "ownership_public_register",
    "ownership_non_res_holdings",
    "ags_secondary_market_turnover_tb",
    "ags_secondary_market_turnover_tib",
    "term_premium_estimates",
    "other_indexaction_factors",
    "other_rmbs_transactions",
    "other_rmbs_auctions",
    "other_interest_rate_swaps",
    "other_cross_currency_swaps",
    "other_portfolio_overview"
  ),
  file.path = c(
    "https://www.aofm.gov.au/media/530",
    "https://www.aofm.gov.au/media/577",
    "https://www.aofm.gov.au/media/579",
    "https://www.aofm.gov.au/media/578",
    "https://www.aofm.gov.au/media/580",
    "https://www.aofm.gov.au/media/581",
    "https://www.aofm.gov.au/media/582",
    "https://www.aofm.gov.au/media/563",
    "https://www.aofm.gov.au/media/564",
    "https://www.aofm.gov.au/media/591",
    "https://www.aofm.gov.au/media/523",
    "https://www.aofm.gov.au/media/632",
    "https://www.aofm.gov.au/media/424",
    "https://www.aofm.gov.au/media/429",
    "https://www.aofm.gov.au/media/631",
    "https://www.aofm.gov.au/media/433",
    "https://www.aofm.gov.au/media/430",
    "https://www.aofm.gov.au/media/566",
    "https://www.aofm.gov.au/media/568",
    "https://www.aofm.gov.au/media/590",
    "https://www.aofm.gov.au/media/589",
    "https://www.aofm.gov.au/media/587",
    "https://www.aofm.gov.au/media/588",
    "https://www.aofm.gov.au/media/575",
    "https://www.aofm.gov.au/media/651",
    "https://www.aofm.gov.au/media/538",
    "https://www.aofm.gov.au/media/527",
    "https://www.aofm.gov.au/media/524",
    "https://www.aofm.gov.au/media/526",
    "https://www.aofm.gov.au/media/522"
  )
  , fn = c(
    "read_eofy",
    "read_eom",
    "read_eom",
    "read_eom",
    "read_eom",
    "read_eom",
    "read_eom",
    "read_eom",
    "read_eom",
    "read_transactional",
    "no function exists",
    "read_syndication",
    "read_transactional",
    "read_transactional",
    "read_syndication",
    "read_transactional",
    "read_transactional",
    "read_transactional",
    "read_transactional",
    "read_ownership",
    "read_ownership",
    "read_secondary",
    "read_secondary",
    "read_premium",
    "no function exists",
    "no function exists",
    "no function exists",
    "no function exists",
    "no function exists",
    "no function exists"
  )
  , file.save = c(
    "eofy_executive_summary.xlsx",
    "eom_portfolio_aggregate_dealt.xlsx",
    "eom_portfolio_aggregate_settlement.xlsx",
    "eom_tb_dealt.xlsx",
    "eom_tb_settlement.xlsx",
    "eom_tib_dealt.xlsx",
    "eom_tib_settlement.xlsx",
    "eom_tn_dealt.xlsx",
    "eom_tn_settlement.xlsx",
    "transactional_tb_issuance_tender_syn.xlsx",
    "transactional_tb_issuance_conversion.xls",
    "transactional_tb_issuance_syn_details.xlsx",
    "transactional_tb_buybacks.xlsx",
    "transactional_tib_issuance_tender_syn.xlsx",
    "transactional_tib_issuance_syn_details.xlsx",
    "transactional_tib_buybacks.xlsx",
    "transactional_tn_issuance.xlsx",
    "transactional_retail_buybacks.xlsx",
    "transactional_securities_lending_facility.xlsx",
    "ownership_public_register.xlsx",
    "ownership_non_res_holdings.xlsx",
    "ags_secondary_market_turnover_tb.xlsx",
    "ags_secondary_market_turnover_tib.xlsx",
    "term_premium_estimates.xlsx",
    "other_indexaction_factors.xlsx",
    "other_rmbs_transactions.xls",
    "other_rmbs_auctions.xlsx",
    "other_interest_rate_swaps.xls",
    "other_cross_currency_swaps.xls",
    "other_portfolio_overview.xlsx"
  )
) 

index_nav <- index %>%
  select(c(4, 6, 1:3)) %>%
  `colnames<-`(c("Argument", "Function", "Category", "Title", "Description"))



##### print index ######

browse_tables <- function(x = index_nav){
  print(x)
}








